## 可以通过设置启动参数  --spring.profiles.active=bb,cc
spring:
  profiles:
    active:
    - rabbit
    - sqlite



######### log   ########################
logging:
  level:
    root: INFO
  config: classpath:logback-spring.xml

######### quartz   ########################
jobs: 
  fixedDelay: 500


---
######### rabbitmq   ########################
spring:
  profiles: rabbit
  rabbitmq:   
    host: 192.168.0.103
    port: 5672
    virtual-host: /
    username: admin
    password: 123456
    template:
      exchange: amq.fanout
      receive-timeout: -1
      #routing-key: myRoutingkey      




---
########### mysql  #######################
spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://10.1.30.8:3306/bim_gis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
## mybatis
mybatis:
  mapperLocations: classpath:mysqlmapper/*.xml





---
######### sqlite #################
spring:
  profiles: sqlite
  datasource:
    url: jdbc:sqlite:sqlitedb/z.db
    driverClassName: org.sqlite.JDBC
## mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml




  
---
######### log   ########################
spring:
  profiles: log
logging:
  level:
    root: ERROR