server:
  port: 8081

## 可以通过设置启动参数  --spring.profiles.active=bb,cc
spring:
  profiles:
    active:
    - sqlite
    - email
    - rabbit



######### log   ########################
logging:
  level:
    root: INFO
  config: classpath:logback-spring.xml

######### quartz   ########################
jobs: 
  fixedDelay: 1500

######### email   ########################
---
spring:
  config:
    activate:
      on-profile: email
  mail:
    #host: pop.qq.com
    host: smtp.qq.com
    username: 617950737@qq.com
    password: rnpvhoraigpzbcdf
    default-encoding: UTF-8
    properties: 
      mail: 
        #pop: 
        smtp:
          auth: true
          starttls:
            enable: true
            required: true



---
######### rabbitmq   ########################
spring:
  config:
    activate:
      on-profile: rabbit
  rabbitmq:   
    host: 192.168.0.103
    port: 5672
    virtual-host: /
    username: admin
    password: 123456
    template:
      exchange: amq.fanout
      receive-timeout: -1
      #routing-key: myRoutingkey      




---
########### mysql  #######################
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://10.1.30.8:3306/bim_gis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
## mybatis
mybatis:
  mapperLocations: classpath:mysqlmapper/*.xml





---
######### sqlite #################
spring:
  config:
    activate:
      on-profile: sqlite
  datasource:
    url: jdbc:sqlite:sqlitedb/z.db
    driverClassName: org.sqlite.JDBC
## mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml




  
---
######### log   ########################
spring:
  config:
    activate:
      on-profile: log
logging:
  level:
    root: ERROR